from .address_shop import *
from .address_cards import *

'''
Card IDs
This connects the shop card addresses and the IDs of the cards when held.
'''
BLANK_CARD = 0
LIFE_CARD = 1
BOMB_CARD = 2
LIFE_FRAGMENT_CARD = 3
BOMB_FRAGMENT_CARD = 4
NAZRIN_CARD = 5
RINGO_CARD = 6
MOKOU_CARD = 7
REIMU1_CARD = 8
REIMU2_CARD = 9
MARISA1_CARD = 10
MARISA2_CARD = 11
SAKUYA1_CARD = 12
SAKUYA2_CARD = 13
SANAE1_CARD = 14
SANAE2_CARD = 15
YOUMU_CARD = 16
ALICE_CARD = 17
CIRNO_CARD = 18
OKINA_CARD = 19
NUE_CARD = 20
NITORI_CARD = 21
KANAKO_CARD = 22
EIRIN_CARD = 23
TEWI_CARD = 24
SAKI_CARD = 25
BYAKUREN_CARD = 26
KOISHI_CARD = 27
SUWAKO_CARD = 28
AYA_CARD = 29
KEIKI_CARD = 30
KAGUYA_CARD = 31
MAMIZOU_CARD = 32
YUYUKO_CARD = 33
YACHIE_CARD = 34
SHIKIEIKI_CARD = 35
NARUMI_CARD = 36
PATCHOULI_CARD = 37
MIKE_CARD = 38
TAKANE_CARD = 39
SANNYO_CARD = 40
YUKARI_CARD = 41
SHINMYOUMARU_CARD = 42
TENSHI_CARD = 43
CLOWNPIECE_CARD = 44
MIKO_CARD = 45
REMILIA_CARD = 46
UTSUHO_CARD = 47
LILYWHITE_CARD = 48
RAIKO_CARD = 49
SUMIREKO_CARD = 50
MISUMARU_CARD = 51
TSUKASA_CARD = 52
MEGUMU_CARD = 53
MOMOYO_CARD = 54
MAGATAMA_CARD = 55

ABILITY_CARD_LIST = [
    BLANK_CARD, LIFE_CARD, BOMB_CARD,
    NAZRIN_CARD, RINGO_CARD, MOKOU_CARD, 
    REIMU1_CARD, REIMU2_CARD, MARISA1_CARD, 
    MARISA2_CARD, SAKUYA1_CARD, SAKUYA2_CARD, 
    SANAE1_CARD, SANAE2_CARD, YOUMU_CARD, 
    ALICE_CARD,CIRNO_CARD, OKINA_CARD, 
    NUE_CARD, NITORI_CARD, KANAKO_CARD, 
    EIRIN_CARD,TEWI_CARD, SAKI_CARD, 
    BYAKUREN_CARD, KOISHI_CARD, SUWAKO_CARD, 
    AYA_CARD, KEIKI_CARD, KAGUYA_CARD, 
    MAMIZOU_CARD, YUYUKO_CARD, YACHIE_CARD, 
    SHIKIEIKI_CARD, NARUMI_CARD, PATCHOULI_CARD, 
    MIKE_CARD, TAKANE_CARD, SANNYO_CARD, 
    YUKARI_CARD, SHINMYOUMARU_CARD, TENSHI_CARD, 
    CLOWNPIECE_CARD, MIKO_CARD, REMILIA_CARD, 
    UTSUHO_CARD,LILYWHITE_CARD, RAIKO_CARD, 
    SUMIREKO_CARD, MISUMARU_CARD, TSUKASA_CARD, 
    MEGUMU_CARD, MOMOYO_CARD
]

# Card Names
BLANK_CARD_NAME = "Blank Card"
LIFE_CARD_NAME = "Life Card"
SPELL_CARD_NAME = "Spell Card"
NAZRIN_CARD_NAME = "Money Comes and Goes On its Own"
RINGO_CARD_NAME = "Ringo-Brand Dango"
MOKOU_CARD_NAME = "Phoenix's Tail"
REIMU1_CARD_NAME = "Yin-Yang Orb"
REIMU2_CARD_NAME = "Yin-Yang Orb (Needle)"
MARISA1_CARD_NAME = "Mini-Hakkero"
MARISA2_CARD_NAME = "Mini-Hakkero (Missile)"
SAKUYA1_CARD_NAME = "Maid Knife"
SAKUYA2_CARD_NAME = "Maid Knife (Ricochet)"
SANAE1_CARD_NAME = "Safe Return Amulet"
SANAE2_CARD_NAME = "Shed Snakeskin Amulet"
YOUMU_CARD_NAME = "Half-Half Ghost"
ALICE_CARD_NAME = "Shanghai Doll"
CIRNO_CARD_NAME = "Ice Fairy"
OKINA_CARD_NAME = "Back Door"
NUE_CARD_NAME = "Annoying UFO"
MISUMARU_CARD_NAME = "Ancient Magatama"
NITORI_CARD_NAME = "Miser's Advice"
KANAKO_CARD_NAME = "Offerings to a Sacred Mountain"
EIRIN_CARD_NAME = "Death Avoidance Elixir"
TEWI_CARD_NAME = "Lucky Rabbit's Foot"
SAKI_CARD_NAME = "Law of the Survival of the Fittest"
BYAKUREN_CARD_NAME = "Sutra of Dharmatic Power"
KOISHI_CARD_NAME = "Pebble Hat"
SUWAKO_CARD_NAME = "Bursting Red Frog"
AYA_CARD_NAME = "Gale Geta"
KEIKI_CARD_NAME = "Idol Defense Corps"
KAGUYA_CARD_NAME = "Princess Kaguya's Secret Stash"
MAMIZOU_CARD_NAME = "Reliable Tanuki Apprentice"
YUYUKO_CARD_NAME = "Danmaku Ghost"
YACHIE_CARD_NAME = "Kiketsu Matriarch's Threat"
SHIKIEIKI_CARD_NAME = "Money Is The Best Lawyer in Hell"
NARUMI_CARD_NAME = "Physical Enhancement Jizo"
PATCHOULI_CARD_NAME = "Spell Before The Fall"
MIKE_CARD_NAME = "Lucky Cat with Good Business Skills"
TAKANE_CARD_NAME = "Yamawaro Shopping Technique"
SANNYO_CARD_NAME = "Dragon Pipe"
MOMOYO_CARD_NAME = "Gluttonous Centipede"
MAGATAMA_CARD_NAME = "Sky-Blue Magatama"
YUKARI_CARD_NAME = "Screen Border"
SHINMYOUMARU_CARD_NAME = "Miracle Mallet"
TENSHI_CARD_NAME = "Keystone of Endurance"
CLOWNPIECE_CARD_NAME = "Moon of Madness"
MIKO_CARD_NAME = "Esteemed Authority"
REMILIA_CARD_NAME = "Vampire Fang"
UTSUHO_CARD_NAME = "Underground Sun"
LILYWHITE_CARD_NAME = "Item Season"
RAIKO_CARD_NAME = "Heavy Bass Drum"
SUMIREKO_CARD_NAME = "Psychokinesis"
TSUKASA_CARD_NAME = "Spirit Power Sample Bottle"
MEGUMU_CARD_NAME = "Great Tengu's Barley Rice"


SHOP_CARD_ID_TO_CARD_ID = {
    BLANK_CARD_SHOP_ADDR : BLANK_CARD,
    LIFE_CARD_SHOP_ADDR : LIFE_CARD,
    SPELL_CARD_SHOP_ADDR : BOMB_CARD,
    NAZRIN_SHOP_ADDR : NAZRIN_CARD,
    RINGO_SHOP_ADDR : RINGO_CARD,
    MOKOU_SHOP_ADDR : MOKOU_CARD,
    MIKE_SHOP_ADDR : MIKE_CARD,
    TAKANE_SHOP_ADDR : TAKANE_CARD,
    SANNYO_SHOP_ADDR : SANNYO_CARD,
    NARUMI_SHOP_ADDR : NARUMI_CARD,
    PATCHOULI_SHOP_ADDR : PATCHOULI_CARD,
    YOUMU_SHOP_ADDR : YOUMU_CARD,
    REIMU_1_SHOP_ADDR : REIMU1_CARD,
    ALICE_SHOP_ADDR : ALICE_CARD,
    CIRNO_SHOP_ADDR : CIRNO_CARD,
    REIMU_2_SHOP_ADDR : REIMU2_CARD,
    MARISA_1_SHOP_ADDR : MARISA1_CARD,
    MARISA_2_SHOP_ADDR : MARISA2_CARD,
    SAKUYA_1_SHOP_ADDR : SAKUYA1_CARD,
    SAKUYA_2_SHOP_ADDR : SAKUYA2_CARD,
    SANAE_1_SHOP_ADDR : SANAE1_CARD,
    SANAE_2_SHOP_ADDR : SANAE2_CARD,
    OKINA_SHOP_ADDR : OKINA_CARD,
    NUE_SHOP_ADDR : NUE_CARD,
    TEWI_SHOP_ADDR : TEWI_CARD,
    EIRIN_SHOP_ADDR : EIRIN_CARD,
    NITORI_SHOP_ADDR : NITORI_CARD,
    SAKI_SHOP_ADDR : SAKI_CARD,
    KOISHI_SHOP_ADDR : KOISHI_CARD,
    KANAKO_SHOP_ADDR : KANAKO_CARD,
    BYAKUREN_SHOP_ADDR : BYAKUREN_CARD,
    SUWAKO_SHOP_ADDR : SUWAKO_CARD,
    AYA_SHOP_ADDR : AYA_CARD,
    KEIKI_SHOP_ADDR : KEIKI_CARD,
    KAGUYA_SHOP_ADDR : KAGUYA_CARD,
    MAMIZOU_SHOP_ADDR : MAMIZOU_CARD,
    YUYUKO_SHOP_ADDR : YUYUKO_CARD,
    YACHIE_SHOP_ADDR : YACHIE_CARD,
    SHIKIEIKI_SHOP_ADDR : SHIKIEIKI_CARD,
    SHINMYOUMARU_SHOP_ADDR : SHINMYOUMARU_CARD,
    YUKARI_SHOP_ADDR : YUKARI_CARD,
    TENSHI_SHOP_ADDR : TENSHI_CARD,
    CLOWNPIECE_SHOP_ADDR : CLOWNPIECE_CARD,
    RAIKO_SHOP_ADDR : RAIKO_CARD,
    MIKO_SHOP_ADDR : MIKO_CARD,
    REMILIA_SHOP_ADDR : REMILIA_CARD,
    UTSUHO_SHOP_ADDR : UTSUHO_CARD,
    LILYWHITE_SHOP_ADDR : LILYWHITE_CARD,
    SUMIREKO_SHOP_ADDR : SUMIREKO_CARD,
    MISUMARU_SHOP_ADDR : MISUMARU_CARD,
    TSUKASA_SHOP_ADDR : TSUKASA_CARD,
    MEGUMU_SHOP_ADDR : MEGUMU_CARD,
    MOMOYO_SHOP_ADDR : MOMOYO_CARD
}

CARD_ID_TO_NAME = {
    BLANK_CARD : BLANK_CARD_NAME,
    LIFE_CARD : LIFE_CARD_NAME,
    BOMB_CARD : SPELL_CARD_NAME,
    NAZRIN_CARD : NAZRIN_CARD_NAME,
    RINGO_CARD : RINGO_CARD_NAME,
    MOKOU_CARD : MOKOU_CARD_NAME,
    MIKE_CARD : MIKE_CARD_NAME,
    TAKANE_CARD : TAKANE_CARD_NAME,
    SANNYO_CARD : SANNYO_CARD_NAME,
    NARUMI_CARD : NARUMI_CARD_NAME,
    PATCHOULI_CARD : PATCHOULI_CARD_NAME,
    YOUMU_CARD : YOUMU_CARD_NAME,
    REIMU1_CARD : REIMU1_CARD_NAME,
    ALICE_CARD : ALICE_CARD_NAME,
    CIRNO_CARD : CIRNO_CARD_NAME,
    REIMU2_CARD : REIMU2_CARD_NAME,
    MARISA1_CARD : MARISA1_CARD_NAME,
    MARISA2_CARD : MARISA2_CARD_NAME,
    SAKUYA1_CARD : SAKUYA1_CARD_NAME,
    SAKUYA2_CARD : SAKUYA2_CARD_NAME,
    SANAE1_CARD : SANAE1_CARD_NAME,
    SANAE2_CARD : SANAE2_CARD_NAME,
    OKINA_CARD : OKINA_CARD_NAME,
    NUE_CARD : NUE_CARD_NAME,
    TEWI_CARD : TEWI_CARD_NAME,
    EIRIN_CARD : EIRIN_CARD_NAME,
    NITORI_CARD : NITORI_CARD_NAME,
    SAKI_CARD : SAKI_CARD_NAME,
    KOISHI_CARD : KOISHI_CARD_NAME,
    KANAKO_CARD : KANAKO_CARD_NAME,
    BYAKUREN_CARD : BYAKUREN_CARD_NAME,
    SUWAKO_CARD : SUWAKO_CARD_NAME,
    AYA_CARD : AYA_CARD_NAME,
    KEIKI_CARD : KEIKI_CARD_NAME,
    KAGUYA_CARD : KAGUYA_CARD_NAME,
    MAMIZOU_CARD : MAMIZOU_CARD_NAME,
    YUYUKO_CARD : YUYUKO_CARD_NAME,
    YACHIE_CARD : YACHIE_CARD_NAME,
    SHIKIEIKI_CARD : SHIKIEIKI_CARD_NAME,
    SHINMYOUMARU_CARD : SHINMYOUMARU_CARD_NAME,
    YUKARI_CARD : YUKARI_CARD_NAME,
    TENSHI_CARD : TENSHI_CARD_NAME,
    CLOWNPIECE_CARD : CLOWNPIECE_CARD_NAME,
    RAIKO_CARD : RAIKO_CARD_NAME,
    MIKO_CARD : MIKO_CARD_NAME,
    REMILIA_CARD : REMILIA_CARD_NAME,
    UTSUHO_CARD : UTSUHO_CARD_NAME,
    LILYWHITE_CARD : LILYWHITE_CARD_NAME,
    SUMIREKO_CARD : SUMIREKO_CARD_NAME,
    MISUMARU_CARD : MISUMARU_CARD_NAME,
    TSUKASA_CARD : TSUKASA_CARD_NAME,
    MEGUMU_CARD : MEGUMU_CARD_NAME,
    MOMOYO_CARD : MOMOYO_CARD_NAME,
    MAGATAMA_CARD : MAGATAMA_CARD_NAME
}

NAME_TO_CARD_ID = {value: key for key, value in CARD_ID_TO_NAME.items()}

CARD_ID_TO_VTABLE_ADDR = {
    BLANK_CARD : VTABLE_BLANKCARD_ADDR,
    LIFE_CARD : VTABLE_LIFE_ADDR,
    BOMB_CARD : VTABLE_BOMB_ADDR,
    NAZRIN_CARD : VTABLE_NAZRIN_ADDR,
    RINGO_CARD : VTABLE_RINGO_ADDR,
    MOKOU_CARD : VTABLE_MOKOU_ADDR,
    MIKE_CARD : VTABLE_MIKE_ADDR,
    TAKANE_CARD : VTABLE_TAKANE_ADDR,
    SANNYO_CARD : VTABLE_SANNYO_ADDR,
    NARUMI_CARD : VTABLE_NARUMI_ADDR,
    PATCHOULI_CARD : VTABLE_PATCHOULI_ADDR,
    YOUMU_CARD : VTABLE_YOUMU_ADDR,
    REIMU1_CARD : VTABLE_REIMU1_ADDR,
    ALICE_CARD : VTABLE_ALICE_ADDR,
    CIRNO_CARD : VTABLE_CIRNO_ADDR,
    REIMU2_CARD : VTABLE_REIMU2_ADDR,
    MARISA1_CARD : VTABLE_MARISA1_ADDR,
    MARISA2_CARD : VTABLE_MARISA2_ADDR,
    SAKUYA1_CARD : VTABLE_SAKUYA1_ADDR,
    SAKUYA2_CARD : VTABLE_SAKUYA2_ADDR,
    SANAE1_CARD : VTABLE_SANAE1_ADDR,
    SANAE2_CARD : VTABLE_SANAE2_ADDR,
    OKINA_CARD : VTABLE_OKINA_ADDR,
    NUE_CARD : VTABLE_NUE_ADDR,
    TEWI_CARD : VTABLE_TEWI_ADDR,
    EIRIN_CARD : VTABLE_EIRIN_ADDR,
    NITORI_CARD : VTABLE_NITORI_ADDR,
    SAKI_CARD : VTABLE_SAKI_ADDR,
    KOISHI_CARD : VTABLE_KOISHI_ADDR,
    KANAKO_CARD : VTABLE_KANAKO_ADDR,
    BYAKUREN_CARD : VTABLE_BYAKUREN_ADDR,
    SUWAKO_CARD : VTABLE_SUWAKO_ADDR,
    AYA_CARD : VTABLE_AYA_ADDR,
    KEIKI_CARD : VTABLE_KEIKI_ADDR,
    KAGUYA_CARD : VTABLE_KAGUYA_ADDR,
    MAMIZOU_CARD : VTABLE_MAMIZOU_ADDR,
    YUYUKO_CARD : VTABLE_YUYUKO_ADDR,
    YACHIE_CARD : VTABLE_YACHIE_ADDR,
    SHIKIEIKI_CARD : VTABLE_SHIKIEIKI_ADDR,
    SHINMYOUMARU_CARD : VTABLE_SHINMYOUMARU_ADDR,
    YUKARI_CARD : VTABLE_YUKARI_ADDR,
    TENSHI_CARD : VTABLE_TENSHI_ADDR,
    CLOWNPIECE_CARD : VTABLE_CLOWNPIECE_ADDR,
    RAIKO_CARD : VTABLE_RAIKO_ADDR,
    MIKO_CARD : VTABLE_MIKO_ADDR,
    REMILIA_CARD : VTABLE_REMILIA_ADDR,
    UTSUHO_CARD : VTABLE_UTSUHO_ADDR,
    LILYWHITE_CARD : VTABLE_LILYWHITE_ADDR,
    SUMIREKO_CARD : VTABLE_SUMIREKO_ADDR,
    MISUMARU_CARD : VTABLE_MISUMARU_ADDR,
    TSUKASA_CARD : VTABLE_TSUKASA_ADDR,
    MEGUMU_CARD : VTABLE_MEGUMU_ADDR,
    MOMOYO_CARD : VTABLE_MOMOYO_ADDR
}

ITEM_CARDS = [LIFE_CARD, BOMB_CARD, NAZRIN_CARD, RINGO_CARD, MOKOU_CARD]

STAGE_EXCLUSIVE_SHOP_CARDS = [MIKE_CARD_NAME, TAKANE_CARD_NAME, SANNYO_CARD_NAME, MISUMARU_CARD_NAME, TSUKASA_CARD_NAME,
                             MEGUMU_CARD_NAME, MOMOYO_CARD_NAME, MAGATAMA_CARD_NAME]



