from .address_shop import *

'''
Card IDs
This connects the shop card addresses and the IDs of the cards when held.
'''
BLANK_CARD = 0
LIFE_CARD = 1
BOMB_CARD = 2
LIFE_FRAGMENT_CARD = 3
BOMB_FRAGMENT_CARD = 4
NAZRIN_CARD = 5
RINGO_CARD = 6
MOKOU_CARD = 7
REIMU1_CARD = 8
REIMU2_CARD = 9
MARISA1_CARD = 10
MARISA2_CARD = 11
SAKUYA1_CARD = 12
SAKUYA2_CARD = 13
SANAE1_CARD = 14
SANAE2_CARD = 15
YOUMU_CARD = 16
ALICE_CARD = 17
CIRNO_CARD = 18
OKINA_CARD = 19
NUE_CARD = 20
NITORI_CARD = 21
KANAKO_CARD = 22
EIRIN_CARD = 23
TEWI_CARD = 24
SAKI_CARD = 25
BYAKUREN_CARD = 26
KOISHI_CARD = 27
SUWAKO_CARD = 28
AYA_CARD = 29
KEIKI_CARD = 30
KAGUYA_CARD = 31
MAMIZOU_CARD = 32
YUYUKO_CARD = 33
YACHIE_CARD = 34
SHIKIEIKI_CARD = 35
NARUMI_CARD = 36
PATCHOULI_CARD = 37
MIKE_CARD = 38
TAKANE_CARD = 39
SANNYO_CARD = 40
YUKARI_CARD = 41
SHINMYOUMARU_CARD = 42
TENSHI_CARD = 43
CLOWNPIECE_CARD = 44
MIKO_CARD = 45
REMILIA_CARD = 46
UTSUHO_CARD = 47
LILYWHITE_CARD = 48
RAIKO_CARD = 49
SUMIREKO_CARD = 50
MISUMARU_CARD = 51
TSUKASA_CARD = 52
MEGUMU_CARD = 53
MOMOYO_CARD = 54
MAGATAMA_CARD = 55

SHOP_CARD_ID_TO_CARD_ID = {
    BLANK_CARD_SHOP_ADDR : BLANK_CARD,
    LIFE_CARD_SHOP_ADDR : LIFE_CARD,
    SPELL_CARD_SHOP_ADDR : BOMB_CARD,
    NAZRIN_SHOP_ADDR : NAZRIN_CARD,
    RINGO_SHOP_ADDR : RINGO_CARD,
    MOKOU_SHOP_ADDR : MOKOU_CARD,
    MIKE_SHOP_ADDR : MIKE_CARD,
    TAKANE_SHOP_ADDR : TAKANE_CARD,
    SANNYO_SHOP_ADDR : SANNYO_CARD,
    NARUMI_SHOP_ADDR : NARUMI_CARD,
    PATCHOULI_SHOP_ADDR : PATCHOULI_CARD,
    YOUMU_SHOP_ADDR : YOUMU_CARD,
    REIMU_1_SHOP_ADDR : REIMU1_CARD,
    ALICE_SHOP_ADDR : ALICE_CARD,
    CIRNO_SHOP_ADDR : CIRNO_CARD,
    REIMU_2_SHOP_ADDR : REIMU2_CARD,
    MARISA_1_SHOP_ADDR : MARISA1_CARD,
    MARISA_2_SHOP_ADDR : MARISA2_CARD,
    SAKUYA_1_SHOP_ADDR : SAKUYA1_CARD,
    SAKUYA_2_SHOP_ADDR : SAKUYA2_CARD,
    SANAE_1_SHOP_ADDR : SANAE1_CARD,
    SANAE_2_SHOP_ADDR : SANAE2_CARD,
    OKINA_SHOP_ADDR : OKINA_CARD,
    NUE_SHOP_ADDR : NUE_CARD,
    TEWI_SHOP_ADDR : TEWI_CARD,
    EIRIN_SHOP_ADDR : EIRIN_CARD,
    NITORI_SHOP_ADDR : NITORI_CARD,
    SAKI_SHOP_ADDR : SAKI_CARD,
    KOISHI_SHOP_ADDR : KOISHI_CARD,
    KANAKO_SHOP_ADDR : KANAKO_CARD,
    BYAKUREN_SHOP_ADDR : BYAKUREN_CARD,
    SUWAKO_SHOP_ADDR : SUWAKO_CARD,
    AYA_SHOP_ADDR : AYA_CARD,
    KEIKI_SHOP_ADDR : KEIKI_CARD,
    KAGUYA_SHOP_ADDR : KAGUYA_CARD,
    MAMIZOU_SHOP_ADDR : MAMIZOU_CARD,
    YUYUKO_SHOP_ADDR : YUYUKO_CARD,
    YACHIE_SHOP_ADDR : YACHIE_CARD,
    SHIKIEIKI_SHOP_ADDR : SHIKIEIKI_CARD,
    SHINMYOUMARU_SHOP_ADDR : SHINMYOUMARU_CARD,
    YUKARI_SHOP_ADDR : YUKARI_CARD,
    TENSHI_SHOP_ADDR : TENSHI_CARD,
    CLOWNPIECE_SHOP_ADDR : CLOWNPIECE_CARD,
    RAIKO_SHOP_ADDR : RAIKO_CARD,
    MIKO_SHOP_ADDR : MIKO_CARD,
    REMILIA_SHOP_ADDR : REMILIA_CARD,
    UTSUHO_SHOP_ADDR : UTSUHO_CARD,
    LILYWHITE_SHOP_ADDR : LILYWHITE_CARD,
    SUMIREKO_SHOP_ADDR : SUMIREKO_CARD,
    MISUMARU_SHOP_ADDR : MISUMARU_CARD,
    TSUKASA_SHOP_ADDR : TSUKASA_CARD,
    MEGUMU_SHOP_ADDR : MEGUMU_CARD,
    MOMOYO_SHOP_ADDR : MOMOYO_CARD
}

CARD_ID_TO_NAME = {
    BLANK_CARD : "Blank Card",
    LIFE_CARD : "Life Card",
    BOMB_CARD : "Spell Card",
    NAZRIN_CARD : "Nazrin",
    RINGO_CARD : "Ringo",
    MOKOU_CARD : "Mokou",
    MIKE_CARD : "Mike",
    TAKANE_CARD : "Takane",
    SANNYO_CARD : "Sannyo",
    NARUMI_CARD : "Narumi",
    PATCHOULI_CARD : "Patchouli",
    YOUMU_CARD : "Youmu",
    REIMU1_CARD : "Reimu 1",
    ALICE_CARD : "Alice",
    CIRNO_CARD : "Cirno",
    REIMU2_CARD : "Reimu 2",
    MARISA1_CARD : "Marisa 1",
    MARISA2_CARD : "Marisa 2",
    SAKUYA1_CARD : "Sakuya 1",
    SAKUYA2_CARD : "Sakuya 2",
    SANAE1_CARD : "Sanae 1",
    SANAE2_CARD : "Sanae 2",
    OKINA_CARD : "Okina",
    NUE_CARD : "Nue",
    TEWI_CARD : "Tewi",
    EIRIN_CARD : "Eirin",
    NITORI_CARD : "Nitori",
    SAKI_CARD : "Saki",
    KOISHI_CARD : "Koishi",
    KANAKO_CARD : "Kanako",
    BYAKUREN_CARD : "Byakuren",
    SUWAKO_CARD : "Suwako",
    AYA_CARD : "Aya",
    KEIKI_CARD : "Keiki",
    KAGUYA_CARD : "Kaguya",
    MAMIZOU_CARD : "Mamizou",
    YUYUKO_CARD : "Yuyuko",
    YACHIE_CARD : "Yachie",
    SHIKIEIKI_CARD : "Eiki",
    SHINMYOUMARU_CARD : "Shinmyoumaru",
    YUKARI_CARD : "Yukari",
    TENSHI_CARD : "Tenshi",
    CLOWNPIECE_CARD : "Clownpiece",
    RAIKO_CARD : "Raiko",
    MIKO_CARD : "Miko",
    REMILIA_CARD : "Remilia",
    UTSUHO_CARD : "Utsuho",
    LILYWHITE_CARD : "Lily White",
    SUMIREKO_CARD : "Sumireko",
    MISUMARU_CARD : "Misumaru",
    TSUKASA_CARD : "Tsukasa",
    MEGUMU_CARD : "Megumu",
    MOMOYO_CARD : "Momoyo"
}

# Card Names
BLANK_CARD_NAME = "Blank Card"





