from .card_constants import *

'''
By Options I am referring to the objects that are made via equipment cards that shoot bullets.
'''

# From the player pointer
EQUIPMENT_OPTION_OFFSET = [0xA30]
EQUIPMENT_OPTION_SIZE = 0xF0
EQUIPMENT_OPTION_Y_OFFSET = 0x68
EQUIPMENT_OPTION_FUNCTION_OFFSET = 0xE8
EQUIPMENT_OPTION_FOLLOW = 0xD8

OPTION_Y_OFFSETS = {
    REIMU1_CARD: 6144,
    REIMU2_CARD: -3072,
    MARISA1_CARD: 2048,
    MARISA2_CARD: 4096,
    SAKUYA1_CARD: 2048,
    SAKUYA2_CARD: 4096,
    SANAE1_CARD: 3584,
    SANAE2_CARD: -2560,
    CIRNO_CARD: -7680,
    OKINA_CARD: 4608,
    YOUMU_CARD: 0,
    ALICE_CARD: 0, 
    NUE_CARD: 0,
    MISUMARU_CARD: 0
}

OPTION_FUNCTION = {
    SAKUYA1_CARD: 0x5DD10,
    YOUMU_CARD: 0x5DDE0,
    ALICE_CARD: 0x0B6D0,
    NUE_CARD: 0x0BD50,
    MISUMARU_CARD: 0x0C080
}

UNIQUE_MOVE_OPTIONS = [SAKUYA1_CARD, YOUMU_CARD, ALICE_CARD, NUE_CARD, MISUMARU_CARD]