from .address_shop import *

'''
General IDs
This connects the shop card addresses and the IDs of the cards when held.
'''

CHARACTER_REIMU = 0
CHARACTER_MARISA = 1
CHARACTER_SAKUYA = 2
CHARACTER_SANAE = 3

CHARACTERS = [CHARACTER_REIMU, CHARACTER_MARISA, CHARACTER_SAKUYA, CHARACTER_SANAE]

DIFFICULTY_EASY = 0
DIFFICULTY_NORMAL = 1
DIFFICULTY_HARD = 2
DIFFICULTY_LUNATIC = 3
DIFFICULTY_EXTRA = 4

DIFFICULTIES = [DIFFICULTY_EASY, DIFFICULTY_NORMAL, DIFFICULTY_HARD, DIFFICULTY_LUNATIC, DIFFICULTY_EXTRA]